<?php

namespace Database\Seeders\Control\Relationships;

use App\Http\Controllers\Control\Role\RoleController;
use App\Models\Control\Role;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionRoleSeeder extends Seeder
{
  public $relationships = [
    'client' => [
      'project_create',
      'project_update',
      'project_state_update',
      'task_create',
      'task_update',
      'task_accept_result',
      'task_reject_result',
      'task_arbitration_request',
      'wallet_deposit',
      'wallet_withdraw',
      'company_control',
      'support_request',
      'chat_create',
      'chat_message',
      'chat_attachment',
      'yourself_access',
    ],
    'moderator' => [
      'task_update_request',
      'task_specialist_request',
      'task_buy_service_request',
      'task_check_request',
      'task_arbitration_request',
      'wallet_deposit',
      'wallet_withdraw',
      'company_send_conf_link',
      'company_validation_state',
      'company_send_conf_link',
      'support_request',
      'chat_create',
      'chat_message',
      'chat_attachment',
      'chat_work_result',
      'specialist_validation_state',
      'specialist_send_conf_link',
      'users_view',
      'anybody_access',
      'specialist_state',
    ],
    'admin' => [
      'task_create',
      'task_update',
      'task_specialist_request',
      'task_specialist_kick',
      'task_buy_service_request',
      'task_state_update',
      'task_check_request',
      'task_accept_result',
      'task_reject_result',
      'task_arbitration_request',
      'wallet_deposit',
      'wallet_withdraw',
      'company_send_conf_link',
      'company_validation_state',
      'company_send_conf_link',
      'support_request',
      'chat_create',
      'chat_message',
      'chat_attachment',
      'chat_state',
      'chat_work_result',
      'specialist_validation_state',
      'specialist_send_conf_link',
      'moderator_create',
      'specialist_create',
      'client_create',
      'moderator_update',
      'specialist_update',
      'client_update',
      'moderator_ban',
      'specialist_ban',
      'client_ban',
      'role_change',
      'users_view',
      'anybody_access',
      'specialist_state',
    ],
    'super_admin' => [
      'project_create',
      'project_update',
      'project_delete',
      'task_create',
      'task_update',
      'task_delete',
      'task_specialist_request',
      'task_specialist_kick',
      'task_buy_service_request',
      'task_state_update',
      'task_check_request',
      'task_accept_result',
      'task_reject_result',
      'task_arbitration_request',
      'wallet_deposit',
      'wallet_withdraw',
      'company_send_conf_link',
      'company_validation_state',
      'company_send_conf_link',
      'support_request',
      'chat_create',
      'chat_message',
      'chat_attachment',
      'chat_state',
      'chat_work_result',
      'specialist_validation_state',
      'specialist_send_conf_link',
      'moderator_create',
      'admin_create',
      'specialist_create',
      'client_create',
      'super_admin_create',
      'arbitration_create',
      'moderator_update',
      'administrator_update',
      'specialist_update',
      'client_update',
      'arbitration_update',
      'moderator_ban',
      'administrator_ban',
      'specialist_ban',
      'client_ban',
      'arbitration_ban',
      'moderator_delete',
      'administrator_delete',
      'specialist_delete',
      'client_delete',
      'role_change',
      'users_view',
      'promocode_create',
      'promocode_delete',
      'yourself_access',
      'anybody_access',
      'specialist_state',
    ],
    'specialist' => [
      'task_specialist_accept',
      'task_check_request',
      'company_control',
      'support_request',
      'chat_create',
      'chat_message',
      'chat_attachment',
      'chat_work_result',
      'specialist_validation_request',
    ],
    'support' => [
      'support_accept_task',
      'support_accept_common',
    ],
    'arbitration' => [
      'arbitration_accept',
      'arbitration_create',
      'arbitartion_decision',
      'arbitration_define_right',
    ]
  ];

  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    foreach ($this->relationships as $roleSlug => $permissions) {
      RoleController::addPermission($roleSlug, $permissions);
    }
  }
}
